#title info
title: "COVID-19 Analysis QC Report"
intro_text: "MultiQC reports summarise analysis results."
report_header_info:
  - Project Type: "COVID-19 Analysis"
  - Sequencing Platform: "MiSeq 2500 High Output V4"
  - Sequencing Setup: "2x150"

#clean sample names
fn_clean_exts:
  - ".gz"
  - ".fastq"
  - "_S"
  - "consensus_"
  - "_[0-1]"

#dragen features
dragen/vc_metrics:
  fn: '*.vc_metrics.csv'
dragen/ploidy_estimation_metrics:
  fn: '*.ploidy_estimation_metrics.csv'
dragen/contig_mean_cov:
  fn_re: '.*\.(wgs|target_bed)_contig_mean_cov_?(tumor|normal)?\.csv'
dragen/coverage_metrics:
  fn_re: '.*\.(wgs|target_bed)_coverage_metrics_?(tumor|normal)?\.csv'
dragen/fine_hist:
  fn_re: '.*\.(wgs|target_bed)_fine_hist_?(tumor|normal)?\.csv'
dragen/fragment_length_hist:
  fn: '*.fragment_length_hist.csv'
dragen/mapping_metrics:
  fn: '*.mapping_metrics.csv'
  contents: >
    Number of unique reads (excl. duplicate
    marked reads)
  num_lines: 50

#pangolin features
pangolin:
  contents: pangolin_version
  num_lines: 1

module order:
        - 'fastQC'
        - 'dragen'
        - 'samtools'
        - 'pangolin'
