# Config file for CECRET / GISAID pipeline
# Update feature below to control pipeline parameters

# cecret_config file to use
cecret_config: "22-02-23_cecret.config"

# date of sequencing run - will become part of final results CSV file
seq_date: "20220102"

# number of sample to be run in each batch
# --miseq runs should be 60 or less
# --nextseq runs should be X or less
batch_limit: "60"

# pangolin version
# to check versions available go to: https://hub.docker.com/r/staphb/pangolin/tags
pangolin_version: "3.1.20-pangolearn-2022-02-02"


