############################### 
# MANDATORY
###############################
################ CECRET
# number of sample to be run in each batch
# --miseq runs should be 55 or less
# --nextseq runs should be 30 or less
batch_limit: "50"

# pangolin version
# to check versions available go to: https://hub.docker.com/r/staphb/pangolin/tags
# 18 for 3.1.18-pangolearn-2022-01-20
# 19 for 3.1.19-pangolearn-2022-01-20
# 20 for 3.1.20-pangolearn-2022-02-02
# 21 for 3.1.20-pangoLearn-2022-02-28
# 22 for 4.1.2-pdata-1.13
# 23 for 4.1.3-pdata-1.15.1
# 24 for 4.1.3-pdata-1.16
# 25 for 4.1.3-pdata-1.17
# 26 for 4.3-pdata-1.20
# 27 for 4.3-pdata-1.21
# 28 for 4.3.1-pdata-1.22
# 29 for 4.3.1-pdata-1.23.1
pangolin_version: "29"

# nextclade version
# to check versions available to go: https://hub.docker.com/r/nextstrain/nextclade/tags
# 1 for nextstrain/nextclade:1.9.0
# 2 for nextstrain/nextclade:1.10.2
# 3 for nextstrain/nextclade:1.10.3
# 4 for nexstrain/nextclade:1.11.0
# 5 for nextstrain/nextclade:2.4.0
# 6 for nextstrain/nextclade:2.7.0
# 7 for nextstrain/nextclade:2.8.0
# 8 for nextstrain/nextclade:2.9.1
# 9 for nextstrain/nextclade:2.14.0
# 10 for nextstrain/nextclade:3.0.0-alpha.0
nextclade_version: "10"

# staphb version
# 1 for 3.10
# 2 for 2.0
# 3 for 3.7.20230613
# 4 for v3.10.20231205
cecret_version: "4"

# cmds
cecret_cmd: 
  aws: "/home/ubuntu/tools/nextflow run /home/ubuntu/workflows/SARS_CoV_2_Workflow/tools/Cecret -profile docker"
  iop: "$HOME/SARS_CoV_2_Workflow/tools/Cecret -profile docker"
basespace_cmd: 
  aws: "/home/ubuntu/tools/basespace"
  iop: "$HOME/basespace"
gisaid_cmd: 
  aws: "/home/ubuntu/.local/bin/cli3"
  iop: "$HOME/cli3"

# reference files
reference_dir:
  aws: "/home/ubuntu/workflows/SARS_CoV_2_Workflow/refs"
  iop: "$HOME/SARS_CoV_2_Workflow/refs"
reference_genome: "MN908947.3.fasta"
reference_gff: "MN908947.3.gff"

# 4 for artic_V4.1_SARS-CoV-2.primer.bed
# 5 for SARS-CoV-2_v5.2.0_1200.primer.bed
primer_version: "5"

# 4 for artic_V4.1_SARS-CoV-2.insert.bed
# 5 for SARS-CoV-2_v5.2.0_1200.insert.bed
insert_version: "5"

# scripts
frag_plot_script: 
  aws: "/home/ubuntu/workflows/SARS_CoV_2_Workflow/scripts/fragment_plots.py"
  iop: "$HOME/scripts/fragment_plots.py"

############# GISAID 
percent_n_cutoff: 50
metadata_file: "metadata.csv"
gisaid_auth: 
  aws: "/home/ubuntu/tools/gisaid/authtokens/gisaid.authtoken"
  iop: "$HOME/gisaid.authton"

submitter: "sevillas2"
type: "betacoronavirus"
passage: "Original"
host: "Human"
gender: "unknown"
patient_status: "unknown"
sequencing_technology: "Illumina Miseq"
originating_lab: "Pathology and Laboratory Medicine Institute, Cleveland Clinic, Ohio, USA"
address_originating: "9500 Euclid Avenue, Cleveland, Ohio 44195, USA"
submitting_lab: "Ohio Department of Health Laboratory"
address_submitting: "8995 East Main Street, Reynoldsburg, Ohio 43068"
authors: "Samantha Sevilla, Eric Brandt, Keoni Omura, Jade Mowery, Michael Weinstein, Clara Zumpetta-Miller, Erica Leasure, Brent Lee"

############# NCBI (attributes)
bioproject_accession: "PRJNA701669"
organism: "Severe acute respiratory syndrome coronavirus 2"
collected_by: "Ohio Department of Health Laboratory"
host: "Homo sapiens"
host_disease: "COVID-19"
isolation_source: "patient isolate"

################ NCBI (metadata)
design_description: "Arctic v4 primers"
filetype: "fastq"
instrument_model: "Illumina MiSeq"
library_strategy: "AMPLICON"
library_source: "VIRAL RNA"
library_selection: "PCR"
library_layout: "single"
platform: "ILLUMINA"

###############################
# Optional
###############################
################ GISAID
additional_location_information: ""
additional_host_information: ""
sampling_strategy: "Baseline surveillance"
specimen_source: ""
outbreak: ""
last_vaccinated: ""
treatment: ""
assembly_method: ""
coverage: ""

################ NCBI (attributes)
antiviral_treatment_agent: ""
collection_device: ""
collection_method: ""
date_of_prior_antiviral_treat: ""
date_of_prior_sars_cov_2_infection: ""
date_of_sars_cov_2_vaccination: ""
exposure_event: ""
geo_loc_exposure: ""
host_age: ""
host_anatomical_material: ""
host_anatomical_part: ""
host_body_product: ""
host_disease_outcome: ""
host_health_state: ""
host_recent_travel_loc: ""
host_recent_travel_return_date: ""
host_sex: ""
host_specimen_voucher: ""
host_subject_id: ""
lat_lon: ""
passage_method: ""
passage_number: ""
prior_sars_cov_2_antiviral_treat: ""
prior_sars_cov_2_infection: ""
prior_sars_cov_2_vaccination: ""
purpose_of_sampling: "baseline surveillance (random sampling)"
purpose_of_sequencing: ""
sars_cov_2_diag_gene_name_1: ""
sars_cov_2_diag_gene_name_2: ""
sars_cov_2_diag_pcr_ct_value_1: ""
sars_cov_2_diag_pcr_ct_value_2: ""
sample_title: ""
sequenced_by: ""
vaccine_received: ""
virus_isolate_of_prior_infection: ""
description: ""

################ NCBI (metadata)
filename3: ""
filename4: ""
assembly: ""
fasta_file: ""
