# Config file for CECRET / GISAID pipeline
# Update feature below to control pipeline parameters

############################### 
# MANDATORY
###############################
################ CECRET
# date of sequencing run - will become part of final results CSV file
seq_date: "20220102"

# number of sample to be run in each batch
# --miseq runs should be 60 or less
# --nextseq runs should be X or less
batch_limit: "60"

# pangolin version
# to check versions available go to: https://hub.docker.com/r/staphb/pangolin/tags
# 18 for 3.1.18-pangolearn-2022-01-20
# 19 for 3.1.19-pangolearn-2022-01-20
# 20 for 3.1.20-pangolearn-2022-02-02
pangolin_version: "18"

############# GISAID 
percent_n: 50
metadata_file: "merged_complete.csv"

submitter: "sevillas2"
type: "betacoronavirus"
passage: "Original"
host: "Human"
gender: "unknown"
patient_status: "unknown"
sequencing_technology: "Illumina Miseq"
submitting_lab: "Ohio Department of Health Laboratory"
address_submitting: "8995 East Main Street, Reynoldsburg, Ohio 43068"
authors: "Jennifer Holmes, Eric Brandt, Keoni Omura, Glen McGillivary, Caitlin McDonnell, Jade Mowery, Stephanie Mccracken, Tyler Payne, Kirtana Ramadugu, Erica Leasure, Brent Lee, Kelsey Florek, Heather Blankenship, Allison Black, Quanta Brown, Tammy Bannerman, Samantha Sevilla"

###############################
# Optional
###############################
################ GISAID
additional_location_information: ""
additional_host_information: ""
sampling_strategy: ""
specimen_source: ""
outbreak: ""
last_vaccinated: ""
treatment: ""
assembly_method: ""
coverage: ""
